### ISSUE TITLE
Astaire doesn't handle the memcache quit command

### ISSUE THREAD

**Issue by rkd-msw** [Metaswitch/astaire#72]
#### Symptoms

Seen in an Astaire log:

```
18-10-2016 16:49:32.354 UTC Warning proxy_server.cpp:288: Unrecognized operation: 7
18-10-2016 16:49:32.409 UTC Warning proxy_server.cpp:288: Unrecognized operation: 7
18-10-2016 16:49:32.409 UTC Warning proxy_server.cpp:288: Unrecognized operation: 7
18-10-2016 16:49:32.410 UTC Warning proxy_server.cpp:288: Unrecognized operation: 7
```

https://github.com/memcached/memcached/wiki/BinaryProtocolRevamped says that 0x07 is QUIT, and that we should acknowledge this and close the connection when we see this.
#### Impact

Log spam.
#### Release and environment

'Onix' release, using Astaire as a memcached proxy instead of just a tap client.
#### Steps to reproduce

Disconnect a memcache client from Astaire.

**Comment by sebrexmetaswitch** [comment]
Closing as fixed in the linked PR
