### ISSUE TITLE
astaire can deadlock with clearwater-cluster-manager

### ISSUE THREAD

**Issue by mirw** [Metaswitch/astaire#76]
#### Symptoms

As discussed in https://github.com/Metaswitch/clearwater-infrastructure/issues/391, astaire can deadlock with clearwater-cluster-manager if we get in a situation where:

* there's no `/etc/clearwater/cluster_settings` file
* clearwater-cluster-manager is blocked calling `service astaire wait-sync`
* astaire isn't running (because there's no `/etc/clearwater/cluster_settings` file)
* `service astaire wait-sync` is blocking (because astaire isn't running).

#### Impact

Astaire never starts running and clearwater-cluster-manager doesn't process further cluster-joining or cluster-leaving actions.  In particular, if clearwater-cluster-manager hasn't yet joined the cluster, it never will..

#### Release and environment 

AIO node from Sandslash release, running under Virtualbox.

#### Steps to reproduce

I don't have a concrete repro, but rebooting the AIO node repeatedly got the system into this state eventually.

**Comment by mirw** [comment]
I think the key question here is what should `service astaire wait-sync` do if astaire isn't running.  Currently wait-sync only returns once it is actually synchronized.  I think it should probably return (with an error code) if astaire isn't running.

This would involve us

* changing cw_stat (in modules/cpp-common/scripts/stats-c) to return failure on timeout
* changing /etc/init.d/astaire to drop out immediately with an error if it gets this error from cw_stat.

We'd then need to check that clearwater-cluster-manager handles this error correctly (probably just by logging and ignoring it).

**Comment by eleanor-merry** [comment]
Fixed by linked PRs
